// Converts the legacy js-objectdetect/jsfeat cascade files (which assign to a
// `camgaze.cascades` global via an IIFE) into typed ES modules under
// src/detect/cascades/. Run with: npm run cascades
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "detect", "cascades");
mkdirSync(outDir, { recursive: true });

const sources = [
  { file: "legacy/cascades/eye.js", name: "eye", exportName: "eyeCascade" },
  {
    file: "legacy/cascades/frontalface.js",
    name: "frontalface",
    exportName: "frontalFaceCascade",
  },
];

for (const { file, name, exportName } of sources) {
  const code = readFileSync(join(root, file), "utf8");
  const sandbox = { camgaze: { cascades: {} } };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox);
  const cascade = sandbox.camgaze.cascades[name];
  if (!cascade || !cascade.complexClassifiers) {
    throw new Error(`No cascade found in ${file}`);
  }
  const ts = [
    "// Generated by scripts/convert-cascade.mjs — do not edit by hand.",
    "// Derived from the js-objectdetect cascades by Martin Tschirsich,",
    "// converted from the OpenCV haarcascade XML files (Intel BSD license).",
    'import type { HaarCascade } from "../haar.js";',
    "",
    `export const ${exportName}: HaarCascade = ${JSON.stringify(cascade)};`,
    "",
    `export default ${exportName};`,
    "",
  ].join("\n");
  writeFileSync(join(outDir, `${name}.ts`), ts);
  console.log(
    `${file} -> src/detect/cascades/${name}.ts (${cascade.complexClassifiers.length} stages)`
  );
}
